title: Xenomorph and Unicorn in the Universe by the Ages
theme: minipa
author: The Predator
email: dallas@weyland-yutani.org
description: > # this means to ignore newlines until "baseurl:"
  Xenomorph description and diet. Relationship with Unicorns.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
